../../RTL/Dual_Port_BRAM.v
../../RTL/PMAU_Full.v
../../RTL/VPU_Result_Requantizer.v
../../RTL/SPU_Quantize_Q8_0.v
../../RTL/SPU_Q8_Scale_Accum.v
../../RTL/SPU_SiLU_Mul.v
../../RTL/SPU_RMSNorm.v
../../RTL/SPU_RoPE.v
../../RTL/SPU_Softmax.v
../../RTL/SPU_Local_Memory.v
../../RTL/SPU_Controller.v
../../RTL/SPU_Top.v
../../RTL/Matrix_Vector_Multiplication.v
../../RTL/AXI4_Mapping.v
../../RTL/MY_IP.v
../../RTL/VPU_Top.v
mult_gen_0_behav.v
../../TESTBENCH/tb_VPU_Top.v
