library verilog;
use verilog.vl_types.all;
entity VPU_Top is
    generic(
        C_S00_AXI_ID_WIDTH: integer := 1;
        C_S00_AXI_DATA_WIDTH: integer := 128;
        C_S00_AXI_ADDR_WIDTH: integer := 40;
        C_S00_AXI_AWUSER_WIDTH: integer := 1;
        C_S00_AXI_ARUSER_WIDTH: integer := 1;
        C_S00_AXI_WUSER_WIDTH: integer := 1;
        C_S00_AXI_RUSER_WIDTH: integer := 1;
        C_S00_AXI_BUSER_WIDTH: integer := 1;
        NUM_LANES       : integer := 16;
        ACT_WIDTH       : integer := 8;
        WEIGHT_WIDTH    : integer := 8;
        ACC_WIDTH       : integer := 32;
        SCALE_WIDTH     : integer := 16;
        SCALE_FRAC_BITS : integer := 15;
        RESULT_FIFO_DEPTH: integer := 8;
        MAX_ROWS        : integer := 128;
        MAX_COL_BEATS   : integer := 256
    );
    port(
        s00_axi_aclk    : in     vl_logic;
        s00_axi_aresetn : in     vl_logic;
        s00_axi_awid    : in     vl_logic_vector;
        s00_axi_awaddr  : in     vl_logic_vector;
        s00_axi_awlen   : in     vl_logic_vector(7 downto 0);
        s00_axi_awsize  : in     vl_logic_vector(2 downto 0);
        s00_axi_awburst : in     vl_logic_vector(1 downto 0);
        s00_axi_awlock  : in     vl_logic;
        s00_axi_awcache : in     vl_logic_vector(3 downto 0);
        s00_axi_awprot  : in     vl_logic_vector(2 downto 0);
        s00_axi_awqos   : in     vl_logic_vector(3 downto 0);
        s00_axi_awregion: in     vl_logic_vector(3 downto 0);
        s00_axi_awuser  : in     vl_logic_vector;
        s00_axi_awvalid : in     vl_logic;
        s00_axi_awready : out    vl_logic;
        s00_axi_wdata   : in     vl_logic_vector;
        s00_axi_wstrb   : in     vl_logic_vector;
        s00_axi_wlast   : in     vl_logic;
        s00_axi_wuser   : in     vl_logic_vector;
        s00_axi_wvalid  : in     vl_logic;
        s00_axi_wready  : out    vl_logic;
        s00_axi_bid     : out    vl_logic_vector;
        s00_axi_bresp   : out    vl_logic_vector(1 downto 0);
        s00_axi_buser   : out    vl_logic_vector;
        s00_axi_bvalid  : out    vl_logic;
        s00_axi_bready  : in     vl_logic;
        s00_axi_arid    : in     vl_logic_vector;
        s00_axi_araddr  : in     vl_logic_vector;
        s00_axi_arlen   : in     vl_logic_vector(7 downto 0);
        s00_axi_arsize  : in     vl_logic_vector(2 downto 0);
        s00_axi_arburst : in     vl_logic_vector(1 downto 0);
        s00_axi_arlock  : in     vl_logic;
        s00_axi_arcache : in     vl_logic_vector(3 downto 0);
        s00_axi_arprot  : in     vl_logic_vector(2 downto 0);
        s00_axi_arqos   : in     vl_logic_vector(3 downto 0);
        s00_axi_arregion: in     vl_logic_vector(3 downto 0);
        s00_axi_aruser  : in     vl_logic_vector;
        s00_axi_arvalid : in     vl_logic;
        s00_axi_arready : out    vl_logic;
        s00_axi_rid     : out    vl_logic_vector;
        s00_axi_rdata   : out    vl_logic_vector;
        s00_axi_rresp   : out    vl_logic_vector(1 downto 0);
        s00_axi_rlast   : out    vl_logic;
        s00_axi_ruser   : out    vl_logic_vector;
        s00_axi_rvalid  : out    vl_logic;
        s00_axi_rready  : in     vl_logic
    );
    attribute mti_svvh_generic_type : integer;
    attribute mti_svvh_generic_type of C_S00_AXI_ID_WIDTH : constant is 2;
    attribute mti_svvh_generic_type of C_S00_AXI_DATA_WIDTH : constant is 2;
    attribute mti_svvh_generic_type of C_S00_AXI_ADDR_WIDTH : constant is 2;
    attribute mti_svvh_generic_type of C_S00_AXI_AWUSER_WIDTH : constant is 2;
    attribute mti_svvh_generic_type of C_S00_AXI_ARUSER_WIDTH : constant is 2;
    attribute mti_svvh_generic_type of C_S00_AXI_WUSER_WIDTH : constant is 2;
    attribute mti_svvh_generic_type of C_S00_AXI_RUSER_WIDTH : constant is 2;
    attribute mti_svvh_generic_type of C_S00_AXI_BUSER_WIDTH : constant is 2;
    attribute mti_svvh_generic_type of NUM_LANES : constant is 2;
    attribute mti_svvh_generic_type of ACT_WIDTH : constant is 2;
    attribute mti_svvh_generic_type of WEIGHT_WIDTH : constant is 2;
    attribute mti_svvh_generic_type of ACC_WIDTH : constant is 2;
    attribute mti_svvh_generic_type of SCALE_WIDTH : constant is 2;
    attribute mti_svvh_generic_type of SCALE_FRAC_BITS : constant is 2;
    attribute mti_svvh_generic_type of RESULT_FIFO_DEPTH : constant is 2;
    attribute mti_svvh_generic_type of MAX_ROWS : constant is 2;
    attribute mti_svvh_generic_type of MAX_COL_BEATS : constant is 2;
end VPU_Top;
